### ISSUE TITLE
Some trouble with geting data from a existed leveldb database.

### ISSUE THREAD

**Issue by xlfsummer** [Level/level#119]
I want get data from a Minecraft world save.
The world is saved using levelDB format.

When I using `getProperty("leveldb.sstables")` I can see it conains a key `"\x00\x00\x00\x00\x00\x00\x00\x00-"`, but I can't retrive the value using `get` method.

![image](https://user-images.githubusercontent.com/20750969/46794797-3776bc80-cd7b-11e8-90ab-17b739a0a3c1.png)

I created a repo for this and here it is:
https://github.com/xlfsummer/leveldb-demo

Thank you.

**Comment by vweevers** [comment]
Looks like binary data, if so, you'll probably want:

```js
const db = level('./db', { keyEncoding: 'binary', valueEncoding: 'binary' })
```

But maybe it's a delimiter internal to the SSTable, idk. You can use a [read stream](https://github.com/Level/level#createReadStream) to get all keys and values.

**Comment by xlfsummer** [comment]
Thank you for your replying.😊

I add the properties you said, but it's not work.
I also tried to use 'createReadStream' method and LevelDown's ‘iterator’ method.
Those methods only retrived a `"~local_player"` key and the value of that key for me.

**Comment by peakji** [comment]
@xlfsummer They’ve modified the [table format](https://github.com/Mojang/leveldb-mcpe/blob/master/table/format.cc) to use zlib instead of the default snappy for compression.
 
We can retrieve the `~local_player` key because it lives in a special young level (also called level-0). Unfortunately, all other keys and values in those ~2MB files are binary-level incompatible with the vanilla leveldb.

However, since the interface didn’t change, you may compile your own leveldown with Mojang’s fork of leveldb.

**Comment by xlfsummer** [comment]
Thank you! That solved my question😊

But in order to try what you said, I may need to learn c plus plus first 😅

**Comment by peakji** [comment]
@xlfsummer Acutally you don't need to code any C++:

1. Clone leveldown
2. Replace leveldb code in the `deps` directory with Mojang’s fork
3. Run `npm build`
4. Voilà!

**Comment by xlfsummer** [comment]
@peakji  Thank you, but It seems not easy as that.

1. I clone both repo and replace the dep/leveldb/leveldb-1.20 with Mojang's leveldb fork
2. I run `npm install`, because there is no `build` script defined.
It throws some error, then I install `node-gyp` and `Python`,
3. I try again, but the compiler throw tons of error. (comile sucessed when using origin leveldb)

![image](https://user-images.githubusercontent.com/20750969/46961267-feb84980-d0d2-11e8-96ce-970148643b2f.png)
The first error says `leveldb::DLLX` is not defined, I have no idea where this thing comes from.

```cpp
namespace leveldb {
  class DLLX Slice {
    //...
  };
};
```
4. I just delete every `DLLX` appeared in code and recompile.

![image](https://user-images.githubusercontent.com/20750969/46962438-bbaba580-d0d5-11e8-9879-94e57019a0d4.png)

Tons of error again.
Now I'm totally fuzzyed. 😵 I don't know what should I do to fix that.

**Comment by peakji** [comment]
@xlfsummer As far as I can remember, there weren't any `DLLX` in the original leveldb source code.

Instead of removing the letters, you may edit the `"sources"` field in the [bingding](https://github.com/Level/leveldown/blob/master/binding.gyp) file to cover all Mojang's additions.

**Comment by clarkx86** [comment]
Thank you very much for this guide @uvwxy! I forked `leveldown` and did every change you suggested, but I get thrown the following errors:
```
> leveldown@5.0.3 install /mnt/c/Users/clark/Cloud/Google Drive/Dokumente/GitHub/Projects/node.js/_playground/leveldb_zlib/node_modules/leveldown
> node-gyp-build

make: Entering directory '/mnt/c/Users/clark/Cloud/Google Drive/Dokumente/GitHub/Projects/node.js/_playground/leveldb_zlib/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o
../deps/leveldb/leveldb-1.20/util/hash.cc: In function ‘uint32_t leveldb::Hash(const char*, size_t, uint32_t)’:
../deps/leveldb/leveldb-1.20/util/hash.cc:37:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       h += static_cast<unsigned char>(data[2]) << 16;
       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/leveldb/leveldb-1.20/util/hash.cc:39:5: note: here
     case 2:
     ^~~~
../deps/leveldb/leveldb-1.20/util/hash.cc:40:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       h += static_cast<unsigned char>(data[1]) << 8;
       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/leveldb/leveldb-1.20/util/hash.cc:42:5: note: here
     case 1:
     ^~~~
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/binding.o
In file included from ../deps/leveldb/leveldb-1.20/include/leveldb/iterator.h:18:0,
                 from ../deps/leveldb/leveldb-1.20/include/leveldb/db.h:10,
                 from ../binding.cc:7:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:25:12: error: variable ‘leveldb::DLLX leveldb::Slice’ has initializer but incomplete type
 class DLLX Slice {
            ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:26:2: error: expected primary-expression before ‘public’
  public:
  ^~~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:26:2: error: expected ‘}’ before ‘public’
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:26:2: error: expected ‘,’ or ‘;’ before ‘public’
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:31:32: error: ISO C++ forbids declaration of ‘Slice’ with no type [-fpermissive]
   Slice(const char* d, size_t n) : data_(d), size_(n) { }
                                ^
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘int leveldb::Slice(const char*, size_t)’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:31:36: error: only constructors take member initializers
   Slice(const char* d, size_t n) : data_(d), size_(n) { }
                                    ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:31:57: warning: no return statement in function returning non-void [-Wreturn-type]
   Slice(const char* d, size_t n) : data_(d), size_(n) { }
                                                         ^
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:34:29: error: ISO C++ forbids declaration of ‘Slice’ with no type [-fpermissive]
   Slice(const std::string& s) : data_(s.data()), size_(s.size()) { }
                             ^
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘int leveldb::Slice(const string&)’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:34:33: error: only constructors take member initializers
   Slice(const std::string& s) : data_(s.data()), size_(s.size()) { }
                                 ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:34:68: warning: no return statement in function returning non-void [-Wreturn-type]
   Slice(const std::string& s) : data_(s.data()), size_(s.size()) { }
                                                                    ^
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:37:22: error: ISO C++ forbids declaration of ‘Slice’ with no type [-fpermissive]
   Slice(const char* s) : data_(s), size_(strlen(s)) { }
                      ^
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘int leveldb::Slice(const char*)’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:37:26: error: only constructors take member initializers
   Slice(const char* s) : data_(s), size_(strlen(s)) { }
                          ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:37:55: warning: no return statement in function returning non-void [-Wreturn-type]
   Slice(const char* s) : data_(s), size_(strlen(s)) { }
                                                       ^
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:40:22: error: non-member function ‘const char* leveldb::data()’ cannot have cv-qualifier
   const char* data() const { return data_; }
                      ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘const char* leveldb::data()’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:40:37: error: ‘data_’ was not declared in this scope
   const char* data() const { return data_; }
                                     ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:40:37: note: suggested alternative: ‘data’
   const char* data() const { return data_; }
                                     ^~~~~
                                     data
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:43:17: error: non-member function ‘size_t leveldb::size()’ cannot have cv-qualifier
   size_t size() const { return size_; }
                 ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘size_t leveldb::size(
’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:43:32: error: ‘size_’ was not declared in this scope
   size_t size() const { return size_; }
                                ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:43:32: note: suggested alternative: ‘size’
   size_t size() const { return size_; }
                                ^~~~~
                                size
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:46:16: error: non-member function ‘bool leveldb::empty()’ cannot have cv-qualifier
   bool empty() const { return size_ == 0; }
                ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘bool leveldb::empty()’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:46:31: error: ‘size_’ was not declared in this scope
   bool empty() const { return size_ == 0; }
                               ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:46:31: note: suggested alternative: ‘size’
   bool empty() const { return size_ == 0; }
                               ^~~~~
                               size
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:50:29: error: non-member function ‘char leveldb::operator[](size_t)’ cannot have cv-qualifier
   char operator[](size_t n) const {
                             ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:50:29: error: ‘char leveldb::operator[](size_t)’ must be a nonstatic member function
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘void leveldb::clear()’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:56:18: error: ‘data_’ was not declared in this scope
   void clear() { data_ = ""; size_ = 0; }
                  ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:56:18: note: suggested alternative: ‘data’
   void clear() { data_ = ""; size_ = 0; }
                  ^~~~~
                  data
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:56:30: error: ‘size_’ was not declared in this scope
   void clear() { data_ = ""; size_ = 0; }
                              ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:56:30: note: suggested alternative: ‘size’
   void clear() { data_ = ""; size_ = 0; }
                              ^~~~~
                              size
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘void leveldb::remove_prefix(size_t)’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:61:5: error: ‘data_’ was not declared in this scope
     data_ += n;
     ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:61:5: note: suggested alternative:
data’
     data_ += n;
     ^~~~~
     data
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:62:5: error: ‘size_’ was not declared in this scope
     size_ -= n;
     ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:62:5: note: suggested alternative:
size’
     size_ -= n;
     ^~~~~
     size
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:66:26: error: non-member function ‘std::__cxx11::string leveldb::ToString()’ cannot have cv-qualifier
   std::string ToString() const { return std::string(data_, size_); }
                          ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘std::__cxx11::string leveldb::ToString()’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:66:53: error: ‘data_’ was not declared in this scope
   std::string ToString() const { return std::string(data_, size_); }
                                                     ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:66:53: note: suggested alternative: ‘data’
   std::string ToString() const { return std::string(data_, size_); }
                                                     ^~~~~
                                                     data
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:66:60: error: ‘size_’ was not declared in this scope
   std::string ToString() const { return std::string(data_, size_); }
                                                            ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:66:60: note: suggested alternative: ‘size’
   std::string ToString() const { return std::string(data_, size_); }
                                                            ^~~~~
                                                            size
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:72:21: error: ‘Slice’ does not name a type
   int compare(const Slice& b) const;
                     ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:72:31: error: non-member function ‘int leveldb::compare(const int&)’ cannot have cv-qualifier
   int compare(const Slice& b) const;
                               ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:75:26: error: ‘Slice’ does not name a type
   bool starts_with(const Slice& x) const {
                          ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:75:36: error: non-member function ‘bool leveldb::starts_with(const int&)’ cannot have cv-qualifier
   bool starts_with(const Slice& x) const {
                                    ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘bool leveldb::starts_with(const int&)’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:76:14: error: ‘size_’ was not declared in this scope
     return ((size_ >= x.size_) &&
              ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:76:14: note: suggested alternative: ‘size’
     return ((size_ >= x.size_) &&
              ^~~~~
              size
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:76:25: error: request for member ‘size_’ in ‘x’, which is of non-class type ‘const int’
     return ((size_ >= x.size_) &&
                         ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:77:21: error: ‘data_’ was not declared in this scope
             (memcmp(data_, x.data_, x.size_) == 0));
                     ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:77:21: note: suggested alternative: ‘data’
             (memcmp(data_, x.data_, x.size_) == 0));
                     ^~~~~
                     data
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:77:30: error: request for member ‘data_’ in ‘x’, which is of non-class type ‘const int’
             (memcmp(data_, x.data_, x.size_) == 0));
                              ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:77:39: error: request for member ‘size_’ in ‘x’, which is of non-class type ‘const int’
             (memcmp(data_, x.data_, x.size_) == 0));
                                       ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:80:2: error: expected unqualified-id before ‘private’
  private:
  ^~~~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:87:30: error: ‘Slice’ does not name a type
 inline bool operator==(const Slice& x, const Slice& y) {
                              ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:87:46: error: ‘Slice’ does not name a type
 inline bool operator==(const Slice& x, const Slice& y) {
                                              ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:87:54: error: ‘bool operator==(const int&, const int&)’ must have an argument of class or enumerated type
 inline bool operator==(const Slice& x, const Slice& y) {
                                                      ^
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:92:30: error: ‘Slice’ does not name a type
 inline bool operator!=(const Slice& x, const Slice& y) {
                              ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:92:46: error: ‘Slice’ does not name a type
 inline bool operator!=(const Slice& x, const Slice& y) {
                                              ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:92:54: error: ‘bool operator!=(const int&, const int&)’ must have an argument of class or enumerated type
 inline bool operator!=(const Slice& x, const Slice& y) {
                                                      ^
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:96:12: error: ‘Slice’ has not been declared
 inline int Slice::compare(const Slice& b) const {
            ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:96:33: error: ‘Slice’ does not name a type
 inline int Slice::compare(const Slice& b) const {
                                 ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:96:43: error: non-member function ‘int compare(const int&)’ cannot have cv-qualifier
 inline int Slice::compare(const Slice& b) const {
                                           ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: In function ‘int compare(const int&)’:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:97:27: error: ‘size_’ was not declared in this scope
   const size_t min_len = (size_ < b.size_) ? size_ : b.size_;
                           ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:97:27: note: suggested alternative:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:82:10: note:   ‘leveldb::size_’
   size_t size_;
          ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:97:37: error: request for member ‘size_’ in ‘b’, which is of non-class type ‘const int’
   const size_t min_len = (size_ < b.size_) ? size_ : b.size_;
                                     ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:97:56: error: request for member ‘size_’ in ‘b’, which is of non-class type ‘const int’
   const size_t min_len = (size_ < b.size_) ? size_ : b.size_;
                                                        ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:98:18: error: ‘data_’ was not declared in this scope
   int r = memcmp(data_, b.data_, min_len);
                  ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:98:27: error: request for member ‘data_’ in ‘b’, which is of non-class type ‘const int’
   int r = memcmp(data_, b.data_, min_len);
                           ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:100:19: error: request for member ‘size_’ in ‘b’, which is of non-class type ‘const int’
     if (size_ < b.size_) r = -1;
                   ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:101:24: error: request for member ‘size_’ in ‘b’, which is of non-class type ‘const int’
     else if (size_ > b.size_) r = +1;
                        ^~~~~
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h: At global scope:
../deps/leveldb/leveldb-1.20/include/leveldb/slice.h:106:1: error: expected declaration before ‘}’ token
 }  // namespace leveldb
 ^
leveldown.target.mk:112: recipe for target 'Release/obj.target/leveldown/binding.o' failed
make: *** [Release/obj.target/leveldown/binding.o] Error 1
make: Leaving directory '/mnt/c/Users/clark/Cloud/Google Drive/Dokumente/GitHub/Projects/node.js/_playground/leveldb_zlib/node_modules/leveldown/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.0-17134-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/c/Users/clark/Cloud/Google Drive/Dokumente/GitHub/Projects/node.js/_playground/leveldb_zlib/node_modules/leveldown
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN leveldb_zlib@1.0.0 No description
npm WARN leveldb_zlib@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@5.0.3 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@5.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Trying to compile on Ubuntu. On Windows it won't even get that far. The following error pops up:
```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\clark\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:281:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\clark\Cloud\Google Drive\Dokumente\GitHub\Projects\node.js\_playground\leveldb_zlib\node_modules\leveldown
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN leveldb_zlib@1.0.0 No description
npm WARN leveldb_zlib@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@5.0.3 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@5.0.3 install script.
```

You can view my fork of `leveldown` and the changes I did [here](https://github.com/clarkx86/leveldown/commits/master).

Thank you and have a wonderful day,
clarkx86 :).
