### ISSUE TITLE
TypeError The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Alecyrus** [Level/level#140]
Node Version： 10.14.2
```
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at dirname (path.js:1268:5)
    at Function.getRoot (webpack:///./node_modules/bindings/bindings.js?:154:13)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:60:32)
    at eval (webpack:///./node_modules/level/node_modules/leveldown/leveldown.js?:4:101)
    at Object../node_modules/level/node_modules/leveldown/leveldown.js (/Users/XXX/dist_electron/index.js:1386:1)
    at __webpack_require__ (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:20:30)
    at eval (webpack:///./node_modules/level/level.js?:1:111)
    at Object../node_modules/level/level.js (/Users/XXX/dist_electron/index.js:1353:1)
    at __webpack_require__ (/Users/XXXdist_electron/index.js:20:30)

```

**Comment by vweevers** [comment]
Can you share the output of `npm ls level levelup leveldown`?

**Comment by Alecyrus** [comment]
![image](https://user-images.githubusercontent.com/13865581/51733013-ffda1900-20ba-11e9-99da-e1f0813957d4.png)

**Comment by vweevers** [comment]
From the stack trace it looks like you're using Webpack to bundle the code for Electron, is that right?

I guess it can't find the native module. You could try using [`externals`](https://webpack.js.org/configuration/externals/), something like:

```
externals: {
  leveldown: 'leveldown'
}
```

**Comment by vweevers** [comment]
Could you share a minimal repro that we can install and (try to) run?

**Comment by Alecyrus** [comment]
I create an issue in electron repo: [#16551](https://github.com/electron/electron/issues/16551)

**Comment by Alecyrus** [comment]
It seem like version problem about electron, level, and webpack. 
* `no webpack 4` + `level 3.0.0` + `electron 3.0.16`: fine
* `no webpack 4` + `level 3.0.0` + `electron 4.0.2`: not work
* `no webpack 4` + `level 5.0.0` + `electron 4.0.2`: fine
* `webpack 4` + `level 5.0.0` + `electron 4.0.2`: not work
``` javascript
 externals: {
      leveldown: 'leveldown',
    },
```

Error:
>  Error: No native build was found for runtime=electron abi=64 platform=darwin arch=x64
    at Function.load.path (webpack:///./node_modules/node-gyp-build/index.js?:42:9)
    at load (webpack:///./node_modules/node-gyp-build/index.js?:16:30)
    at eval (webpack:///./node_modules/leveldown/binding.js?:1:101)
    at Object../node_modules/leveldown/binding.js (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:1329:1)
    at __webpack_require__ (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:20:30)
    at eval (webpack:///./node_modules/leveldown/leveldown.js?:3:17)
    at Object../node_modules/leveldown/leveldown.js (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:1362:1)
    at __webpack_require__ (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:20:30)
    at eval (webpack:///./node_modules/level/level.js?:1:111)
    at Object../node_modules/level/level.js (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:1318:1)

**Comment by Alecyrus** [comment]
https://github.com/electron/electron/issues/16551#issuecomment-457792077

**Comment by Alecyrus** [comment]
There is a minimal repro that help you guys to reproduce
https://github.com/Alecyrus/electron-level-minimal
```sh
$ git clone https://github.com/Alecyrus/electron-level-minimal.git
$ cd electron-level-minimal
$ yarn
$ yarn electron:service
```
You'll see the error in Chrome devtools console
![image](https://user-images.githubusercontent.com/13865581/51781606-e1752b80-2155-11e9-9393-922c138b4c75.png)

**Comment by Alecyrus** [comment]
**Solved**, @vweevers  you are right. It can't find the native module. But we should set external in `electron builder` rather than `webpack` config. 
```javascript
// vue.config.js
module.exports = {
  configureWebpack: {
  },
  pluginOptions: {
    electronBuilder: {
      externals: ['level'],
    },
  },
};
```

**Comment by ralphtheninja** [comment]
@Alecyrus Good that you reported this and solved it on your own. This is useful for other people running into similar issues.

**Comment by lcc91** [comment]
I has been stuck for 2 days. After I saw this thread, I solved the problem!
Remind who came this thread, I'm using https://github.com/pouchdb/pouchdb which also depend on "leveldown".
And, solve by adding this in webpack config
` externals: {
      leveldown: 'leveldown',
    },`
