### ISSUE TITLE
No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.17.0 webpack=true

### ISSUE THREAD

**Issue by dominusmars** [Level/level#246]
I wanted to work with level in my next js application but i keep getting this error on two computers, on both windows and fedora. 

```shell
Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.17.0 webpack=true
    loaded from: /home//gits/books/.next/server/vendor-chunks

    at load.resolve.load.path (webpack-internal:///(rsc)/./node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (webpack-internal:///(rsc)/./node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at eval (webpack-internal:///(rsc)/./node_modules/classic-level/binding.js:1:107)
    at (rsc)/./node_modules/classic-level/binding.js (/home//gits/books/.next/server/vendor-chunks/classic-level.js:19:1)
    at __webpack_require__ (/home//gits/books/.next/server/webpack-runtime.js:33:43)
    ```

**Comment by NaNOteh** [comment]
> I wanted to work with level in my next js application but i keep getting this error on two computers, on both windows and fedora.
> 
> ```shell
> Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.17.0 webpack=true
>     loaded from: /home//gits/books/.next/server/vendor-chunks
> 
>     at load.resolve.load.path (webpack-internal:///(rsc)/./node_modules/node-gyp-build/node-gyp-build.js:60:9)
>     at load (webpack-internal:///(rsc)/./node_modules/node-gyp-build/node-gyp-build.js:22:30)
>     at eval (webpack-internal:///(rsc)/./node_modules/classic-level/binding.js:1:107)
>     at (rsc)/./node_modules/classic-level/binding.js (/home//gits/books/.next/server/vendor-chunks/classic-level.js:19:1)
>     at __webpack_require__ (/home//gits/books/.next/server/webpack-runtime.js:33:43)
>     ```
> ```

**Comment by QuentinPhrl** [comment]
No update for this ? I have the same problem
