### ISSUE TITLE
Module version mismatch. Expected 46, got 48

### ISSUE THREAD

**Issue by Melvillian** [Level/level#39]
While developing on OSX 10.11.6 I had no problems interfacing with levelDB. However when I deployed my app to an Ubuntu 14.04 box and tried to insert something into the database I received the following error. Downgrading `level` to 1.3.0 doesn't change anything.

```
/home/ubuntu/dev/ka-tet/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/home/ubuntu/dev/ka-tet/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/ubuntu/dev/ka-tet/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/dev/ka-tet/node_modules/level/level.js:1:106)
    at Module._compile (module.js:409:26)
```

**Comment by juliangruber** [comment]
You seem to have installed level with a different node version than you are running it. Try either to `npm install level` or `cd node_modules level && npm install` on the deployment machine or building it for the desired node version on your development machine. This problem will occur with any native dependency, it's nothing level related.

**Comment by Melvillian** [comment]
Yep, looks like my nvm aliases were messed up. It's working now, thanks!
